Repository FRONTENDBOOTCAMP-13th/Final-11-Cutie, pull requests merged in 2025-08, with the labels that each got.

#214 Feature/213-profileeditimg-pjw
  src/app/(main)/accounts/components/ProfileFunction.tsx
  src/app/(main)/edit/ProfileImageSection.tsx
  src/components/common/Header.tsx
Labels: ✨ Feature

#217 Feature/186-signup-pjw
  src/app/(user)/signup/signupForm.tsx
Labels: ✨ Feature

#221 Feature/220-login
  src/app/(user)/login/InitUserLogin.tsx
  src/app/(user)/login/LoginForm.tsx
  src/app/(user)/login/page.tsx
  src/zustand/userStore.ts
Labels: ✨ Feature, 🔨 Refactor, 🦋BugFix

#226 UI/209 headernavigation
  src/app/(main)/products/[id]/edit/EditProduct.tsx
  src/app/(main)/products/new/detail/ProjectContent.tsx
  src/components/common/Header.tsx
  src/zustand/useEditProjectStore.ts
Labels: 🎨 Html&css, 🦋BugFix

#227 Feature/205-pay-pjw
  src/app/(main)/products/[id]/ProductSummary.tsx
  src/components/address/DeliveryAddress.tsx
  src/components/common/Header.tsx
  src/components/common/etc.tsx
  src/zustand/orderStore.ts
Labels: ✨ Feature

#234 Feature/228-checkoutmodal-pjw
  src/app/(simple)/checkout/AddCard.tsx
  src/app/(simple)/checkout/Address.tsx
  src/app/(simple)/checkout/CheckoutMethod.tsx
  src/components/button/SquareBtn.tsx
  src/components/common/etc.tsx
  src/zustand/addressStore.ts
  src/zustand/cardStore.ts
Labels: ✨ Feature

#239 🐛 bug fix
  src/app/(main)/products/[id]/reviews/ReviewSection.tsx
Labels: 🦋BugFix

#241 Feature/232 productdetaildata
  api/dbinit/team/data.json
  src/app/(main)/products/[id]/ComingSoonProduct.tsx
  src/app/(main)/products/[id]/EndProduct.tsx
  src/app/(main)/products/[id]/NotSuccessEndProduct.tsx
  src/app/(main)/products/[id]/ProductIdClient.tsx
  src/app/(main)/products/[id]/ProductSummary.tsx
  src/app/(main)/products/[id]/edit/EditProduct.tsx
  src/components/product/ProductItem.tsx
  src/types/product.ts
  src/utils/goalPercent.ts
Labels: ✨ Feature, 🦋BugFix

#242 Feature/223 headernav
  src/app/(main)/products/ProductPageClient.tsx
  src/app/(main)/products/[id]/edit/EditProduct.tsx
  src/app/(main)/products/new/NewProduct.tsx
  src/app/(main)/products/new/page.tsx
  src/components/common/Header.tsx
  src/data/functions/product.ts
Labels: ✨ Feature

#244 Feature/207 main page
  src/app/(main)/MainProductItem.tsx
  src/app/(main)/page.tsx
  src/app/(main)/products/ProductPageClient.tsx
  src/components/common/etc.tsx
  src/components/product/ProductItem.tsx
Labels: ✨ Feature

#257 Feature/236 new project register
  src/app/(main)/accounts/fund/FundPageTab.tsx
  src/app/(main)/accounts/fund/loading.tsx
  src/app/(main)/accounts/fund/page.tsx
Labels: ✨ Feature

#258 Feature/250 mainbookmark
  src/app/(main)/MainProductItem.tsx
  src/app/(main)/MainProductList.tsx
  src/app/(main)/page.tsx
  src/app/(main)/products/[id]/ComingSoonProduct.tsx
  src/app/(main)/products/[id]/EndProduct.tsx
  src/app/(main)/products/[id]/NotSuccessEndProduct.tsx
  src/app/(main)/products/[id]/ProductSummary.tsx
  src/app/(user)/login/LoginForm.tsx
  src/components/button/LikeBtn.tsx
  src/components/product/ProductItem.tsx
  src/data/functions/like.ts
  src/data/functions/product.ts
  src/zustand/userStore.ts
Labels: ✨ Feature, 🔨 Refactor, 🦋BugFix

#263 UI/253 UI
  src/app/(main)/refund/page.tsx
  src/components/common/Header.tsx
Labels: 🎨 Html&css

#264 Fix/262-mainskeleton
  src/app/(main)/MainProductItem.tsx
  src/app/(main)/MainProductList.tsx
  src/app/(main)/products/ProductPageClient.tsx
  src/components/product/ProductItem.tsx
Labels: 🎨 Html&css, 🦋BugFix

#266 💄Modal position modification
  src/app/(simple)/checkout/page.tsx
  src/components/common/Header.tsx
  src/components/modal/Modal.tsx
Labels: 🎨 Html&css

#267 📸 add images-bsb
  README.md
  src/assets/images/dororo.png
  src/assets/images/giroro.png
  src/assets/images/keroro.png
  src/assets/images/kururu.png
  src/assets/images/tamama.png
Labels: 📃 Docs

#280 Refactor/273-profileedit-pjw
  src/app/(main)/edit/ProfileForm.tsx
Labels: ✨ Feature

#288 Fix/285-banner(margintop)-pjw
  src/app/(main)/page.tsx
Labels: 🎨 Html&css

#294 fix/293-producteditvalid
  api/dbinit/team/data.json
  src/app/(main)/products/[id]/edit/EditProduct.tsx
  src/data/functions/product.ts
Labels: 🦋BugFix

#296 📝 modify readme-bsb
  README.md
Labels: 📃 Docs

#302 Bug/300 mainpage text
  src/app/(main)/products/new/detail/NewProductDetail.tsx
  src/components/product/ProductItem.tsx
Labels: 🐞 Bug

#303 Bug/301-makeproject-pjw
  src/app/(main)/accounts/myReview/writeReview/WriteReviewForm.tsx
  src/app/(main)/products/new/detail/ProjectCategory.tsx
  src/app/(main)/products/new/detail/RegisterCon.tsx
  src/app/(simple)/checkout/CheckoutMethod.tsx
Labels: 🦋BugFix

#309 ✨ quantity: Number(formData.get('quantity')) || 999,
  src/data/actions/seller.ts
Labels: 🔨 Refactor

#312 fix category
  src/components/button/RoundedBtn.tsx
Labels: 🚨 HotFix
