Repository FRONTENDBOOTCAMP-13th/Final-11-Cutie, pull requests merged in 2025-07, with the labels that each got.

#18 pr:ui/12-heder,hedermenu-ktk
  src/app/layout.tsx
  src/components/button/SquareBtn.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/etc.tsx
Labels: 🎨 Html&css

#23 🔧 setting svg webpack #15
  next.config.ts
  package-lock.json
  package.json
  svgr.d.ts
  tsconfig.json
Labels: ⚙ Setting

#43 ui/19-header component-ktk
  public/icons/logo.svg
  src/assets/icons/category.svg
  src/assets/icons/categoryall.svg
  src/assets/icons/clothes.svg
  src/assets/icons/food.svg
  src/assets/icons/game.svg
  src/assets/icons/home.svg
  src/assets/icons/kids.svg
  src/assets/icons/phrase.svg
  src/assets/icons/prefume.svg
  src/assets/icons/search.svg
  src/assets/icons/specialseason.svg
  src/assets/icons/tech.svg
  src/assets/icons/unprofile.svg
  src/components/common/Header.tsx
Labels: 🎨 Html&css

#46 💡 add comment
  src/app/globals.css
Labels: 🚨 HotFix

#44 pr:UI/29-componentdetailedproduct-pjw
  src/assets/icons/heartbox.svg
  src/assets/icons/sharebox.svg
  src/components/product/ProductSummary.tsx
Labels: 🎨 Html&css

#47 ui/28-header component logn-ktk
  src/app/page.tsx
  src/assets/icons/profile.svg
  src/components/common/Header.tsx
Labels: 🎨 Html&css

#59 UI/33 component
  src/components/address/DeliveryAddress.tsx
  src/components/button/SquareBtn.tsx
  src/components/common/etc.tsx
  src/components/menu/Category.tsx
  src/components/product/ProductItem.tsx
Labels: 🎨 Html&css

#61 UI/37-component-kjs
  src/assets/icons/checkbox.svg
  src/assets/icons/uncheckbox.svg
  src/components/address/DeliveryAddress.tsx
  src/components/button/SquareBtn.tsx
  src/components/cart/CartItem.tsx
  src/components/common/CommonItem.tsx
Labels: 🎨 Html&css

#55 PR: UI/41-component-pjw
  src/components/common/Header.tsx
Labels: 🎨 Html&css

#76 UI/68-pageproductlist-bsb
  src/app/(main)/products/page.tsx
  src/assets/icons/chevron-right.svg
  src/assets/icons/heart-empty.svg
  src/assets/icons/heart-fill.svg
  src/assets/icons/toggle-arrow-down.svg
  src/assets/icons/toggle-arrow-up.svg
  src/components/menu/Category.tsx
  src/components/menu/FilterToggle.tsx
  src/components/product/ProductItem.tsx
Labels: 🎨 Html&css

#81 UI/64 pagemain
  public/images/banner.png
  public/images/banner.svg
  src/app/(main)/page.tsx
  src/app/globals.css
  src/components/common/etc.tsx
  src/components/menu/Category.tsx
  src/components/menu/FilterToggle.tsx
  src/components/product/ProductItem.tsx
Labels: 🎨 Html&css

#84 🐛 fix bug
  src/components/menu/FilterToggle.tsx
Labels: 🦋BugFix

#79 UI/65-pageloginsignup-kjs
  src/app/(main)/accounts/myBuy/page.tsx
  src/app/(main)/edit/page.tsx
  src/app/(main)/edit/profileEditForm.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/login/loginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/page.tsx
  src/app/(user)/signup/signupForm.tsx
  src/app/layout.tsx
  src/assets/icons/kakao.svg
  src/assets/icons/naver.svg
  src/components/button/SquareBtn.tsx
  src/components/common/Input.tsx
  src/components/term/TermsBtn.tsx
  tsconfig.json
Labels: 🎨 Html&css

#90 UI/73 pagesearchpage
  src/app/search/page.tsx
  src/components/common/Footer.tsx
Labels: 🎨 Html&css

#89 UI/67-pagemakeproject-pjw
  src/app/(main)/products/new/page.tsx
  src/assets/images/makeproject.svg
  src/components/button/RoundedBtn.tsx
  src/components/button/SquareBtn.tsx
  src/components/common/etc.tsx
Labels: 🎨 Html&css

#93 UI/74 pageerrorpage-bsb
  src/app/layout.tsx
  src/app/not-found.tsx
  src/assets/images/keroroShock.png
Labels: 🎨 Html&css

#99 UI/72 pagemypage
  src/app/(main)/accounts/layout.tsx
  src/app/(main)/accounts/page.tsx
  src/app/(main)/edit/profileEditForm.tsx
Labels: 🎨 Html&css

#102 UI/96-pagemypagetab-pjw
  src/app/(main)/accounts/layout.tsx
  src/app/(main)/accounts/page.tsx
Labels: 🎨 Html&css

#101 UI/98 pageeditprofile
  src/app/(main)/edit/page.tsx
  src/app/(main)/edit/profileEditForm.tsx
Labels: 🎨 Html&css

#111 Uipage/107-mypagelayout-pjw
  src/app/(main)/accounts/layout.tsx
  src/app/(main)/accounts/page.tsx
Labels: 🦋BugFix

#106 💄 MyReviewTab
  src/app/(main)/accounts/cart/page.tsx
  src/app/(main)/accounts/fund/page.tsx
  src/app/(main)/accounts/myReview/page.tsx
  src/components/tab/categoryTab.tsx
Labels: 🎨 Html&css

#115 🐛 fix bug
  src/app/(main)/products/[id]/page.tsx
  src/app/(main)/products/page.tsx
  src/app/api/account/route.ts
  src/app/api/cart/route.ts
  src/app/api/checkout/route.ts
  src/app/api/notification/route.ts
  src/app/api/product/[id]/route.ts
  src/app/api/product/route.ts
  src/app/api/review/[id]/route.ts
  src/app/api/review/route.ts
  src/components/common/etc.tsx
  src/components/product/ProductItem.tsx
Labels: 🦋BugFix

#127 Bug/123-checkout-pjw
  src/app/(simple)/checkout/page.tsx
  src/components/common/etc.tsx
Labels: 🦋BugFix

#136 fix/135-fixdata-setting
  api/dbinit/team/data.js
  src/components/product/ProductItem.tsx
  src/types/product.ts
Labels: 🦋BugFix

#138 Bug/131 fixuseclient-bsb
  src/app/(main)/products/page.tsx
  src/components/menu/Category.tsx
  src/components/menu/FilterToggle.tsx
  src/components/product/ProductItem.tsx
Labels: 🎨 Html&css, 🦋BugFix

#142 Feature/140 filtertogglecategory-bsb
  src/app/(main)/products/pageClient.tsx
  src/components/menu/Category.tsx
  src/components/menu/FilterToggle.tsx
Labels: ✨ Feature

#145 Feature/144-registerbankmodal
  src/app/etc/page.tsx
  src/components/checkbox/CircleCheckbox.tsx
  src/components/modal/Modal.tsx
Labels: ✨ Feature

#155 Feature/120 checkoutpageclick-ktk
  src/app/(simple)/checkout/AddCard.tsx
  src/app/(simple)/checkout/Address.tsx
  src/app/(simple)/checkout/CheckoutMethod.tsx
  src/app/(simple)/checkout/page.tsx
  src/components/address/DeliveryAddress.tsx
  src/components/common/etc.tsx
  src/components/modal/card/CardModal.tsx
Labels: 🎨 Html&css

#158 🐛 fixed: modal click
  src/app/(simple)/checkout/CheckoutMethod.tsx
  src/components/address/DeliveryAddress.tsx
  src/components/modal/Modal.tsx
Labels: 🦋BugFix

#160 Feature/148 category save-ktk
  src/app/(main)/products/new/detail/NewProductDetail.tsx
  src/app/(main)/products/new/detail/page.tsx
  src/app/(main)/products/new/page.tsx
  src/components/button/RoundedBtn.tsx
  src/zustand/userCategory.ts
Labels: ✨ Feature

#163 Feature/141-readtermmodal-pjw
  src/app/(main)/products/new/page.tsx
  src/components/term/TermsBtn.tsx
  src/components/term/TermsModal.tsx
Labels: ✨ Feature

#166 Feature/156 modal
  src/app/(main)/products/new/detail/NewProductDetail.tsx
  src/app/(main)/products/new/detail/RegisterBank.tsx
  src/app/(main)/products/new/detail/RegisterBtnModal.tsx
  src/app/(main)/products/new/detail/RegisterCon.tsx
  src/app/(main)/products/new/detail/RegisterTax.tsx
  src/components/button/SquareBtn.tsx
  src/components/product/ProductCreatorInfo.tsx
Labels: ✨ Feature, 🎨 Html&css

#169 ✨ Stay logged in feature
  src/app/(user)/login/InitUserLogin.tsx
  src/app/(user)/login/loginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/layout.tsx
  src/components/button/SquareBtn.tsx
  src/components/common/Input.tsx
  src/zustand/userStore.ts
Labels: ✨ Feature

#173 Feature/172-banner-pjw
  src/app/(main)/MainBanner.tsx
  src/app/(main)/accounts/components/ProfileFunction.tsx
  src/app/(main)/accounts/layout.tsx
  src/app/(main)/page.tsx
  src/app/(user)/login/LoginSection.tsx
  src/app/(user)/login/page.tsx
Labels: ✨ Feature, 🦋BugFix

#189 Feature/181 notification-bsb
  src/app/(main)/accounts/components/AlertMessage.tsx
Labels: ✨ Feature, 🎨 Html&css

#191 🔀 Merge pull Feature/161 product
  api/bruno/fundream/01_회원/01_회원가입,로그인/판매 회원 로그인(_id=2).bru
  api/bruno/fundream/01_회원/04_회원 정보 조회/지정한 회원 정보 조회(모든 속성).bru
  api/bruno/fundream/01_회원/04_회원 정보 조회/지정한 회원 정보 조회에 데이터 추가.bru
  api/bruno/fundream/02_상품/판매 상품 조회.bru
  api/bruno/fundream/02_상품/판매 상품 추가.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/01_목록 조회/folder.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/게시물 등록.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/게시물 삭제.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/게시물 상세 조회.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/게시물 수정.bru
  api/bruno/fundream/05_게시판(QnA, 공지 등)/사진 업로드.bru
  src/app/(main)/products/new/detail/NewProductDetail.tsx
  src/app/(main)/products/new/detail/ProjectCategory.tsx
  src/app/(main)/products/new/detail/ProjectIntro.tsx
  src/app/(main)/products/new/detail/ProjectPlan.tsx
  src/app/(main)/products/new/detail/ProjectThumbnail.tsx
  src/app/(main)/products/new/detail/RegisterBtnModal.tsx
  src/app/(main)/products/new/detail/react.quill.tsx
  src/components/button/RoundedBtn.tsx
  src/components/common/Input.tsx
  src/components/form/form.tsx
  src/components/menu/Category.tsx
  src/components/product/ProductItem.tsx
  src/data/actions/seller.ts
  src/types/product.ts
  src/zustand/useProjectStore.ts
  src/zustand/userCategory.ts
Labels: ✨ Feature

#195 Feature/184 spinner-bsb
  src/app/(main)/accounts/cart/loading.tsx
  src/app/(main)/accounts/fund/loading.tsx
  src/app/(main)/accounts/loading.tsx
  src/app/(main)/accounts/myReview/loading.tsx
  src/app/(main)/products/new/loading.tsx
  src/app/(simple)/checkout/loading.tsx
  src/app/search/loading.tsx
Labels: 🎨 Html&css

#197 Bug/193 category
  api/bruno/fundream/02_상품/상품 검색.bru
  src/app/(main)/products/ProductPageClient.tsx
  src/components/common/Header.tsx
  src/components/product/ProductItem.tsx
  src/data/actions/seller.ts
  src/data/functions/product.ts
  src/types/product.ts
Labels: ✨ Feature, 🦋BugFix

#199 feature/194-porducts commont add-ktk
  api/bruno/fundream/02_상품/상품 한개 조회.bru
  src/app/(main)/products/[id]/ProductSummary.tsx
  src/app/(main)/products/new/detail/RegisterBtnModal.tsx
  src/components/button/SquareBtn.tsx
  src/types/product.ts
Labels: ✨ Feature

#201 Feature/170 search
  src/app/(main)/products/[id]/ProductIdClient.tsx
  src/app/search/PopularKeywords.tsx
  src/app/search/SearchFunction.tsx
  src/app/search/page.tsx
  src/components/common/Header.tsx
  src/components/common/Searchbar.tsx
  src/utils/keywordUtils.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor
